### ISSUE TITLE
[DOC] Create Documentation for Git and GitHub Usage

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/DevToolsArena#203]
### Create Documentation for Git and GitHub Usage

**Description:**
Please create a Markdown file containing comprehensive documentation for using Git and GitHub. This file should include an overview of common commands, best practices, and troubleshooting tips.

**Requirements:**
1. The documentation should be written in Markdown format and saved in the `/posts` folder.
2. Ensure the documentation covers the following topics:
   - Basic Git commands (init, clone, add, commit, etc.)
   - Branching and merging strategies
   - Working with remote repositories (fetch, pull, push)
   - Handling merge conflicts
   - Using GitHub for collaboration (forking, pull requests, issues, etc.)
   - Tips for maintaining a clean commit history

3. Update the `index.json` file in the `/posts` folder:
   - Add an entry for the new documentation file, including a title that reflects the content (e.g., "Git and GitHub Usage Guide").

**Additional Notes:**
- Please ensure the documentation is clear, concise, and well-structured.
- Include examples where applicable to illustrate the concepts.

This documentation will be a valuable resource for both new and experienced contributors to the project. Thank you!

**Comment by jump3rhood** [comment]
Can you assign this to me? I want to work on this. Will help me get acquainted with contributing.

**Comment by devvsakib** [comment]
Hi @jump3rhood , can you give me an estimate time how long it will take?

**Comment by jump3rhood** [comment]
Hi @devvsaki, working on it. Is it cool if i take 2 days? I want it to be comprehensive.

**Comment by devvsakib** [comment]
@jump3rhood sure, no worries. we are working on new resources page, so take your time
