### ISSUE TITLE
Text Visibility in Light Mode

### ISSUE THREAD

**Issue by PATILYASHH** [devvsakib/DevToolsArena#237]
#### Description
In the light mode of our website, the text within modal or pop-up windows is not visible due to insufficient contrast between the text color and the background color. This makes it difficult for users to read the content and interact with the provided solutions effectively.

#### Steps to Reproduce
1. Open the website and switch to light mode.
2. Trigger any modal or pop-up window by clicking on the error tags (e.g., "push," "merge").
3. Observe that the text within the modal or pop-up window is not visible or is hard to read.

#### Expected Behavior
The text within the modal or pop-up windows should be clearly visible and easily readable in light mode, with sufficient contrast between the text color and the background color.

#### Screenshots
![image](https://github.com/user-attachments/assets/58ddea4f-4bff-4950-865b-4036b4fd5a25)

#### Suggested Solution
1. **Change Text Color:** Adjust the text color within the modal or pop-up windows to ensure it contrasts well with the background. For example, use a darker text color on a light background.
2. **Adjust Background Color:** Modify the background color of the modal or pop-up windows to be darker if the text is light, or vice versa.
3. **Add Shadows or Borders:** Adding shadows or borders around the modal can help it stand out against the background and improve text visibility.

**Comment by devvsakib** [comment]
add border to solution btn as well
![image](https://github.com/user-attachments/assets/90b0b6d2-639c-4358-a076-534ccfc5dea5)

**Comment by PATILYASHH** [comment]
Got it

**Comment by PATILYASHH** [comment]
#244 issue solved check the PR
