### ISSUE TITLE
Add space in buttons

### ISSUE THREAD

**Issue by PATILYASHH** [devvsakib/DevToolsArena#248]
Add Some space in both buttons 

![image](https://github.com/user-attachments/assets/dd5895d6-f7a6-4268-b335-e7d9707f69be)

Soluton - 

code-
:where(.css-1uq9j6g).ant-btn-default {
    background: #ffffff;
    border-color: #d9d9d9;
    color: rgba(0, 0, 0, 0.88);
    box-shadow: 0 2px 0 rgb(0 0 0 / 2%);
}
add 
`margin : 3px; `

after adding -
![image](https://github.com/user-attachments/assets/f69c3f64-86f9-4365-8afb-5f7f7e7c03c9)

**Comment by PATILYASHH** [comment]
assign me for this issue

**Comment by devvsakib** [comment]
don't overwrite css, use tailwind css in button. 
use a parent div for these 3 button and use flex, gap,
