### ISSUE TITLE
contributing.md need to update 

### ISSUE THREAD

**Issue by PATILYASHH** [devvsakib/DevToolsArena#256]
You Changed your repository name `github-error-solve` to `evToolsArena` but contribution.md file is still old

**Comment by YB-24** [comment]
Hello sir, I want to contribute in this project by helping in the documentation.
Can you assign this issue to me?

**Comment by PATILYASHH** [comment]
> Hello sir, I want to contribute in this project by helping in the documentation.
> Can you assign this issue to me?

I already PR it .

**Comment by PATILYASHH** [comment]
> Hello sir, I want to contribute in this project by helping in the documentation.
> Can you assign this issue to me?

Are u a new on GitHub

**Comment by PATILYASHH** [comment]
@YB-24, you can solve this issue better than I did in my PR. I only changed the links and names. If you're interested, you can solve the issue by replacing the screenshots with ones that have the current website name.

**Comment by YB-24** [comment]
Yes sir I am new on GitHub and finding some good first issues to solve.
I will change images as well after this issue is assigned to me.

**Comment by PATILYASHH** [comment]
> Yes sir I am new on GitHub and finding some good first issues to solve.
> I will change images as well after this issue is assigned to me.

Start work on issue
