### ISSUE TITLE
Improve Text Visibility and Contrast in Light Mode for Error Cards

### ISSUE THREAD

**Issue by PATILYASHH** [devvsakib/DevToolsArena#263]
### Dark mode -
![image](https://github.com/user-attachments/assets/999bdf52-d9c3-4947-bf8e-1380f0cee3dc)

### Light Mode

![image](https://github.com/user-attachments/assets/a828f183-27e9-4837-9900-f399d505b033)

**Comment by Pratham-Gaikwad** [comment]
hi! I would like to work on this issue

**Comment by annuk123** [comment]
I want to work on this issue

**Comment by devvsakib** [comment]
Assigned to you @annuk123
